import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { mount, flushPromises } from '@vue/test-utils'
import { reactive } from 'vue'
import CopySvgButton from './CopySvgButton.vue'

describe('CopySvgButton', () => {
  beforeEach(() => {
    vi.useFakeTimers()
    // Mock navigator.clipboard if not available
    if (!navigator.clipboard) {
      navigator.clipboard = {}
    }
    navigator.clipboard.writeText = vi.fn()
  })

  afterEach(() => {
    vi.restoreAllMocks()
    vi.useRealTimers()
  })

  function createWrapper(state = {}) {
    const defaultState = reactive({
      canvas: {
        parameters: null,
        svg: {
          points: [],
          controlPoints: [],
          paths: []
        }
      },
      ...state
    })

    return mount(CopySvgButton, {
      global: {
        provide: {
          state: defaultState
        }
      }
    })
  }

  it('is disabled when no canvas parameters', () => {
    const wrapper = createWrapper()
    expect(wrapper.find('button').attributes('disabled')).toBeDefined()
  })

  it('is enabled when canvas parameters exist', () => {
    const wrapper = createWrapper({
      canvas: {
        parameters: { width: 1000, height: 800 },
        svg: {
          points: [],
          controlPoints: [],
          paths: []
        }
      }
    })
    expect(wrapper.find('button').attributes('disabled')).toBeUndefined()
  })

  it('shows "Copy SVG" text initially', () => {
    const wrapper = createWrapper({
      canvas: {
        parameters: { width: 1000, height: 800 },
        svg: {
          points: [[0, 0], [100, 100]],
          controlPoints: [],
          paths: [
            { type: 'line', points: [0, 1], controlPoints: [] }
          ]
        }
      }
    })
    expect(wrapper.text()).toBe('Copy SVG')
  })

  it('copies SVG string to clipboard when clicked', async () => {
    navigator.clipboard.writeText.mockResolvedValueOnce(undefined)

    const wrapper = createWrapper({
      canvas: {
        parameters: { width: 1000, height: 800 },
        svg: {
          points: [[0, 0], [100, 100]],
          controlPoints: [],
          paths: [
            { type: 'line', points: [0, 1], controlPoints: [] }
          ]
        }
      }
    })

    await wrapper.find('button').trigger('click')
    await flushPromises()

    expect(navigator.clipboard.writeText).toHaveBeenCalled()
    const copiedText = navigator.clipboard.writeText.mock.calls[0][0]
    expect(copiedText).toContain('<svg')
    expect(copiedText).toContain('<!-- generated by tracer -->')
  })

  it('shows "✓ Copied" after successful copy', async () => {
    navigator.clipboard.writeText.mockResolvedValue(undefined)

    const wrapper = createWrapper({
      canvas: {
        parameters: { width: 1000, height: 800 },
        svg: {
          points: [[0, 0], [100, 100]],
          controlPoints: [],
          paths: [
            { type: 'line', points: [0, 1], controlPoints: [] }
          ]
        }
      }
    })

    await wrapper.find('button').trigger('click')
    await flushPromises()

    expect(wrapper.text()).toBe('✓ Copied')
  })

  it('reverts to "Copy SVG" after 2 seconds', async () => {
    navigator.clipboard.writeText.mockResolvedValue(undefined)

    const wrapper = createWrapper({
      canvas: {
        parameters: { width: 1000, height: 800 },
        svg: {
          points: [[0, 0], [100, 100]],
          controlPoints: [],
          paths: [
            { type: 'line', points: [0, 1], controlPoints: [] }
          ]
        }
      }
    })

    await wrapper.find('button').trigger('click')
    await flushPromises()

    expect(wrapper.text()).toBe('✓ Copied')

    vi.advanceTimersByTime(2000)
    await wrapper.vm.$nextTick()

    expect(wrapper.text()).toBe('Copy SVG')
  })
})
