const TRACER_VERSION = '1.0'

function renderPath(path, points, controlPoints) {
  const [x1, y1] = points[path.points[0]]
  const [x2, y2] = points[path.points[1]]

  if (path.type === 'line') {
    return `  <path d="M ${x1} ${y1} L ${x2} ${y2}" />`
  } else if (path.type === 'cubicBezier') {
    const [cx1, cy1] = controlPoints[path.controlPoints[0]]
    const [cx2, cy2] = controlPoints[path.controlPoints[1]]
    return `  <path d="M ${x1} ${y1} C ${cx1} ${cy1} ${cx2} ${cy2} ${x2} ${y2}" />`
  }
}

export function generateSvgString(canvasParams, svgData) {
  if (!canvasParams || !svgData) return null

  const { width, height } = canvasParams
  const pathElements = svgData.paths
    .map(path => renderPath(path, svgData.points, svgData.controlPoints))
    .join('\n')

  return `<svg viewBox="0 0 ${width} ${height}" data-tracer-version="${TRACER_VERSION}" xmlns="http://www.w3.org/2000/svg">
  <!-- generated by tracer -->
${pathElements}
</svg>`
}
