import { describe, it, expect } from 'vitest'
import { generateSvgString } from './svgGenerator'

describe('generateSvgString', () => {
  it('returns null when canvasParams is missing', () => {
    const svgData = {
      points: [],
      controlPoints: [],
      paths: []
    }
    expect(generateSvgString(null, svgData)).toBeNull()
  })

  it('returns null when svgData is missing', () => {
    const canvasParams = { width: 1000, height: 800 }
    expect(generateSvgString(canvasParams, null)).toBeNull()
  })

  it('includes svg opening tag with viewBox and version attribute', () => {
    const canvasParams = { width: 1000, height: 800 }
    const svgData = {
      points: [],
      controlPoints: [],
      paths: []
    }
    const svg = generateSvgString(canvasParams, svgData)
    expect(svg).toContain('<svg')
    expect(svg).toContain('viewBox="0 0 1000 800"')
    expect(svg).toContain('data-tracer-version="1.0"')
    expect(svg).toContain('xmlns="http://www.w3.org/2000/svg"')
  })

  it('includes generated by tracer comment', () => {
    const canvasParams = { width: 1000, height: 800 }
    const svgData = {
      points: [],
      controlPoints: [],
      paths: []
    }
    const svg = generateSvgString(canvasParams, svgData)
    expect(svg).toContain('<!-- generated by tracer -->')
  })

  it('renders a single line path correctly', () => {
    const canvasParams = { width: 1000, height: 800 }
    const svgData = {
      points: [[100, 200], [300, 400]],
      controlPoints: [],
      paths: [
        { type: 'line', points: [0, 1], controlPoints: [] }
      ]
    }
    const svg = generateSvgString(canvasParams, svgData)
    expect(svg).toContain('<path d="M 100 200 L 300 400" />')
  })

  it('renders multiple line paths', () => {
    const canvasParams = { width: 1000, height: 800 }
    const svgData = {
      points: [[100, 200], [300, 400], [500, 600]],
      controlPoints: [],
      paths: [
        { type: 'line', points: [0, 1], controlPoints: [] },
        { type: 'line', points: [1, 2], controlPoints: [] }
      ]
    }
    const svg = generateSvgString(canvasParams, svgData)
    expect(svg).toContain('<path d="M 100 200 L 300 400" />')
    expect(svg).toContain('<path d="M 300 400 L 500 600" />')
  })

  it('renders a cubic bezier path correctly', () => {
    const canvasParams = { width: 1000, height: 800 }
    const svgData = {
      points: [[100, 200], [500, 600]],
      controlPoints: [[200, 300], [400, 500]],
      paths: [
        { type: 'cubicBezier', points: [0, 1], controlPoints: [0, 1] }
      ]
    }
    const svg = generateSvgString(canvasParams, svgData)
    expect(svg).toContain('<path d="M 100 200 C 200 300 400 500 500 600" />')
  })

  it('renders mixed line and bezier paths', () => {
    const canvasParams = { width: 1000, height: 800 }
    const svgData = {
      points: [[0, 0], [100, 100], [200, 200]],
      controlPoints: [[50, 50], [150, 150]],
      paths: [
        { type: 'line', points: [0, 1], controlPoints: [] },
        { type: 'cubicBezier', points: [1, 2], controlPoints: [0, 1] }
      ]
    }
    const svg = generateSvgString(canvasParams, svgData)
    expect(svg).toContain('<path d="M 0 0 L 100 100" />')
    expect(svg).toContain('<path d="M 100 100 C 50 50 150 150 200 200" />')
  })

  it('generates valid SVG structure', () => {
    const canvasParams = { width: 1000, height: 800 }
    const svgData = {
      points: [[0, 0], [100, 100]],
      controlPoints: [],
      paths: [
        { type: 'line', points: [0, 1], controlPoints: [] }
      ]
    }
    const svg = generateSvgString(canvasParams, svgData)
    expect(svg).toMatch(/<svg[\s\S]*<\/svg>/)
  })

  it('does not include point symbols', () => {
    const canvasParams = { width: 1000, height: 800 }
    const svgData = {
      points: [[0, 0], [100, 100]],
      controlPoints: [],
      paths: [
        { type: 'line', points: [0, 1], controlPoints: [] }
      ]
    }
    const svg = generateSvgString(canvasParams, svgData)
    expect(svg).not.toContain('rect')
  })

  it('does not include control point symbols', () => {
    const canvasParams = { width: 1000, height: 800 }
    const svgData = {
      points: [[0, 0], [100, 100]],
      controlPoints: [[25, 25], [75, 75]],
      paths: [
        { type: 'cubicBezier', points: [0, 1], controlPoints: [0, 1] }
      ]
    }
    const svg = generateSvgString(canvasParams, svgData)
    expect(svg).not.toContain('rect')
  })
})
